apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/frontend

namespace: shopsecure-prod

images:
  - name: 887998956998.dkr.ecr.us-east-1.amazonaws.com/shopsecure/frontend
    newName: 887998956998.dkr.ecr.us-east-1.amazonaws.com/shopsecure/frontend
    newTag: latest
