apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: shopsecure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: ShopSecure E-Commerce Platform

  sourceRepos:
    - "https://github.com/Gavok-Devops/Shopsecure-devsecops-project"
    - "https://github.com/Gavok-Devops/Shopsecure-devsecops-project.git"

  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: shopsecure-prod
      server: https://kubernetes.default.svc
    - namespace: shopsecure-staging
      server: https://kubernetes.default.svc
    - namespace: shopsecure-dev
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: jenkins
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRole
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRoleBinding
    - group: "argoproj.io"
      kind: Application

  roles:
    - name: developer
      policies:
        - p, proj:shopsecure:developer, applications, sync, shopsecure/*, allow
        - p, proj:shopsecure:developer, applications, get, shopsecure/*, allow
    - name: admin
      policies:
        - p, proj:shopsecure:admin, applications, *, shopsecure/*, allow
