apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/order-service

namespace: shopsecure-prod

images:
  - name: REGISTRY/order-service
    newName: .dkr.ecr.us-east-1.amazonaws.com/shopsecure/order-service
    newTag: latest
