apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: shopsecure-prod
  labels:
    app: product-service
    monitoring: enabled
spec:
  selector:
    app: product-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-service
  namespace: shopsecure-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam:::role/shopsecure-product-service-role
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: product-service
  namespace: shopsecure-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product-service
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 4
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 25
          periodSeconds: 60
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: product-service
  namespace: shopsecure-prod
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: product-service
