apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopsecure-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: shopsecure
  source:
    repoURL: https://github.com/YOUR_ORG/shopsecure-gitops
    targetRevision: main
    path: kubernetes/argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
