apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/product-service

namespace: shopsecure-prod

images:
  - name: 887998956998.dkr.ecr.us-east-1.amazonaws.com/shopsecure/product-service
    newName: 887998956998.dkr.ecr.us-east-1.amazonaws.com/shopsecure/product-service
    newTag: latest  # Updated by Jenkins via sed

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: product-service
